/** Rotating guest facts while an order is preparing (~1600 entries). */
export const WAIT_FACTS: readonly string[] = [
  "Pickling eggs gets more aromatic if spices bloom in fat first.",
  "Lima is famous for ceviche and Pacific creativity — a reminder that place seasons food.",
  "Soap on modern seasoned cast iron is fine in moderation.",
  "Krachai is a fingerroot used in Thai herbal dishes.",
  "Braising beef tastes cleaner when you do not crowd the pan.",
  "Pickling chicken builds deeper flavour than rushing the pan.",
  "A dry wipe often cleans mushrooms better than a soak.",
  "Pickling eggs shows off when salt is measured thoughtfully.",
  "Binchotan charcoal burns clean and hot for yakitori.",
  "Roasting prawns pairs well with a bright acid at the end.",
  "00 flour is finely milled — great for pizza and pasta.",
  "Honey in dressings adds body and gentle sweetness.",
  "Galangal looks like ginger but tastes sharper and piney.",
  "Cast iron holds heat — brilliant for searing, slower to cool.",
  "Smoking tofu gets more aromatic if spices bloom in fat first.",
  "Braising tofu pairs well with a bright acid at the end.",
  "Katsu curry pours Japanese curry over a fried cutlet.",
  "Braising tofu loves a rest before you slice or serve.",
  "Grilling mushrooms rewards patience more than constant poking.",
  "Steaming tofu gets more aromatic if spices bloom in fat first.",
  "Century eggs are preserved to a creamy, amber interior.",
  "Higher hydration doughs make open crumb and stickier hands.",
  "Fermenting eggs tastes cleaner when you do not crowd the pan.",
  "Coffee grounds scrub pans and deodorise hands after garlic.",
  "Bay leaf in rice pilaf is a quiet background note.",
  "Scaloppine are thin cutlets cooked quickly.",
  "Star anise tastes like liquorice because of anethole.",
  "Fermenting paneer builds deeper flavour than rushing the pan.",
  "Roasting fish loves a rest before you slice or serve.",
  "Labneh with olive oil and za’atar is breakfast simplicity.",
  "Kaffir lime leaves perfume Thai curries with floral citrus.",
  "Sambar’s tang often comes from tamarind.",
  "Beurre noisette is butter browned until nutty.",
  "Frying beef rewards patience more than constant poking.",
  "Fermenting fish keeps moisture when you respect temperature.",
  "Pickling pork loves a rest before you slice or serve.",
  "Bombes mould ice cream into decorative spheres.",
  "Grilling chicken keeps moisture when you respect temperature.",
  "Blanching sets colour in green vegetables before shocking in ice.",
  "Store herbs like bouquets in water for longer life.",
  "Ghee is butter with milk solids cooked out.",
  "Roasting lamb tastes cleaner when you do not crowd the pan.",
  "Chilled cookie dough spreads less and tastes deeper.",
  "Deep frying surrounds food with hot oil for even crust.",
  "Biltong is air-dried meat from southern Africa, often thicker than jerky.",
  "Ginger-garlic paste stains plastic cutting boards.",
  "Smoking tofu rewards patience more than constant poking.",
  "Kochi is famous for coconut, spice routes, and toddy-shop lore — a reminder that place seasons food.",
  "Roasting chicken builds deeper flavour than rushing the pan.",
  "Grilling lamb gets more aromatic if spices bloom in fat first.",
  "Fermenting chicken rewards patience more than constant poking.",
  "Jalapeño poppers hide cheese inside fried chili heat.",
  "Aspic is savoury jelly set with gelatine from bones or sheets.",
  "Jaggery softens dals and balances chili heat.",
  "The danger zone for bacteria is roughly 5–60°C.",
  "Roasting beef tastes cleaner when you do not crowd the pan.",
  "Fresh basil softens when warmed gently in oil.",
  "While you wait, picture a kitchen in Lucknow: slow kebabs and elegant Awadhi cooking.",
  "Cappuccino aims for a balance of espresso, milk, and foam.",
  "Fermenting pork pairs well with a bright acid at the end.",
  "Börek covers many filled pastry traditions across the region.",
  "Gingerols in ginger are why it soothes queasy stomachs.",
  "Thin blue smoke is often the goal for clean barbecue.",
  "Creaming butter and sugar traps air for lighter cakes.",
  "Braising eggs pairs well with a bright acid at the end.",
  "Smoking beef shows off when salt is measured thoughtfully.",
  "Shocking in ice water stops carryover cooking in greens.",
  "Grilling paneer tastes cleaner when you do not crowd the pan.",
  "Roasting prawns keeps moisture when you respect temperature.",
  "Sandesh moulds can imprint flowers and patterns.",
  "Roasting beef builds deeper flavour than rushing the pan.",
  "Gari is the thin pink pickled ginger at sushi counters.",
  "Cumin seeds darken quickly — keep the spoon moving.",
  "Lotus leaves perfume sticky rice parcels when steamed.",
  "Steam-peeling tomatoes slips skins after a quick blanch.",
  "Grilling fish gets more aromatic if spices bloom in fat first.",
  "Grilling paneer rewards patience more than constant poking.",
  "Satay skewers travel with peanut sauce across Southeast Asia.",
  "Indian pickles often cure in the sun for weeks.",
  "Braising paneer keeps moisture when you respect temperature.",
  "Bananas continue ripening after picking thanks to ethylene.",
  "Deglazing lifts browned flavour stuck to a hot pan.",
  "Fresh oregano brightens grilled vegetables.",
  "Baking eggs rewards patience more than constant poking.",
  "Pickling paneer tastes cleaner when you do not crowd the pan.",
  "Frying paneer rewards patience more than constant poking.",
  "Sol kadhi is kokum and coconut milk, cooling and pink.",
  "Robata grilling uses charcoal at a high, focused heat.",
  "Agar comes from red algae and sets vegetarian jellies.",
  "Caprese is mozzarella, tomato, and basil in season.",
  "Smoking tofu tastes cleaner when you do not crowd the pan.",
  "Braising beef shows off when salt is measured thoughtfully.",
  "Smoking paneer builds deeper flavour than rushing the pan.",
  "Smoking mushrooms loves a rest before you slice or serve.",
  "Muthiya are steamed dumplings later tempered or fried.",
  "Water just off the boil suits most pour-overs.",
  "Roasting mushrooms tastes cleaner when you do not crowd the pan.",
  "Wontons can float in soup or fry into crispy parcels.",
  "Au poivre sauces are peppery cream or cognac pan sauces.",
  "Colour-coded boards help busy kitchens stay safe.",
  "Molasses is the dark syrup left after sugar crystallisation.",
  "Baking pork tastes cleaner when you do not crowd the pan.",
  "Fish cakes bind flaked fish with potato or crumbs.",
  "Braising tofu shows off when salt is measured thoughtfully.",
  "Gyudon is simmered beef bowl comfort.",
  "While you wait, picture a kitchen in Naples: pizza dough and tomato simplicity.",
  "Macaroons are coconut mounds, often Passover-friendly.",
  "Fresh chives turns plain yogurt into a quick sauce.",
  "Saucepans are smaller and have long handles.",
  "Arborio, carnaroli, and vialone nano are risotto classics.",
  "Dorayaki sandwiches red bean paste between pancakes.",
  "There are thousands of named apple cultivars worldwide.",
  "Hollandaise is the emulsion mother sauce.",
  "Habaneros are close cousins to Scotch bonnets.",
  "Soubise folds onion into béchamel.",
  "Roasting beef shows off when salt is measured thoughtfully.",
  "Amchur is dried green mango powder — tart and fruity.",
  "Freshly milled flour tastes sweeter and ferments eagerly.",
  "Frying eggs keeps moisture when you respect temperature.",
  "Salt-cured egg yolks grate like cheese over pasta.",
  "Braising prawns shows off when salt is measured thoughtfully.",
  "Steaming paneer loves a rest before you slice or serve.",
  "Lardo is cured fatback sliced paper thin.",
  "Chopped liver is a Jewish spread of cooked liver and onions.",
  "Steaming fish shows off when salt is measured thoughtfully.",
  "Frying tofu gets more aromatic if spices bloom in fat first.",
  "A squeeze of lime wakes grilled corn and fish.",
  "Roasting pork pairs well with a bright acid at the end.",
  "Bonbons are filled chocolates with thin shells.",
  "Fresh thyme turns plain yogurt into a quick sauce.",
  "Filter coffee in South India drips strong and mixes with milk.",
  "Coffee rubs on brisket add roasted bitterness that balances fat.",
  "Pierogi are Polish dumplings boiled then often pan-fried.",
  "Hayashi rice is a western-influenced demi-glace beef bowl.",
  "Puttanesca is bold with olives, capers, and anchovy.",
  "Pan con tomate is bread rubbed with tomato and oil.",
  "Daughter sauces are variations built on mother sauces.",
  "Bird’s eye chili is small and fierce.",
  "Bundt pans need thorough greasing in every ridge.",
  "Omurice wraps fried rice in a soft omelette.",
  "Poaching prawns gets more aromatic if spices bloom in fat first.",
  "Rillettes are meat cooked in fat until shreddable.",
  "Kewpie mayo is tangier and yolk-richer than many mayos.",
  "Pandans leaf perfumes Southeast Asian rice and cakes.",
  "Roasting lamb shows off when salt is measured thoughtfully.",
  "Panettone is a tall Milanese celebration bread.",
  "Bangkok is famous for balance of sweet, sour, salty, and heat — a reminder that place seasons food.",
  "Goddess chutney is bright with coconut, herbs, and chili.",
  "Croquetas are Spanish bechamel fritters.",
  "Bamboo is hard and knife-dulling compared with softer woods.",
  "Cooking with leftover coffee intensifies chocolate cakes.",
  "Braising tofu gets more aromatic if spices bloom in fat first.",
  "Smoking lamb keeps moisture when you respect temperature.",
  "Amazake is a sweet, low-or-no alcohol rice drink.",
  "Mishti doi is sweet set yogurt from Bengal.",
  "Bagna cauda is hot garlic-anchovy dip from Piedmont.",
  "Tomato water is a clear, fragrant liquid from salted chopped tomatoes.",
  "Pretzels’ dark skin often comes from a lye or baking-soda bath.",
  "Smoking fish builds deeper flavour than rushing the pan.",
  "Soba is buckwheat, often mixed with wheat for strength.",
  "Ganache is chocolate emulsified with hot cream.",
  "Bondas hide spiced potato inside a chickpea shell.",
  "A latte is espresso stretched with steamed milk.",
  "Steaming paneer pairs well with a bright acid at the end.",
  "Angel food pans have feet so cakes cool upside down.",
  "Poaching pork rewards patience more than constant poking.",
  "Tsukemen is noodles dipped into a separate rich broth.",
  "Poaching tofu gets more aromatic if spices bloom in fat first.",
  "Hibachi at home often means a small grill, not the restaurant show.",
  "Poaching lamb tastes cleaner when you do not crowd the pan.",
  "Steam ovens keep breads springy and vegetables bright.",
  "Moroccan tagines trap steam under a cone-shaped lid.",
  "Salsa roja is cooked red salsa; verde is tomatillo-based.",
  "Poaching fish builds deeper flavour than rushing the pan.",
  "Dondurma is stretchy Turkish ice cream with salep and mastic.",
  "Bottarga is cured fish roe grated over pasta like hard cheese.",
  "Fresh oregano can stand in for salad greens in a pinch.",
  "Pickling fish rewards patience more than constant poking.",
  "Watermelon is one of the most hydrating fruits by weight.",
  "Convection fans brown more evenly by moving hot air.",
  "Horseradish is pungent when grated fresh and fades with time.",
  "Poaching tofu shows off when salt is measured thoughtfully.",
  "Macchiatos are espresso “stained” with a little milk foam.",
  "Poaching chicken rewards patience more than constant poking.",
  "Fresh wasabi rhizomes are grated on sharkskin graters traditionally.",
  "Frying pork loves a rest before you slice or serve.",
  "Braising chicken rewards patience more than constant poking.",
  "Braising paneer tastes cleaner when you do not crowd the pan.",
  "Churros pipe dough into hot oil and roll in sugar.",
  "Smoking prawns pairs well with a bright acid at the end.",
  "Korma is a gently spiced, often nut-thickened braise.",
  "Carbonara traditionally uses eggs, guanciale, and cheese — no cream.",
  "Fermenting beef builds deeper flavour than rushing the pan.",
  "Everything bagel seasoning is garlic, onion, sesame, and poppy.",
  "Baking mushrooms keeps moisture when you respect temperature.",
  "While you wait, picture a kitchen in Chengdu: tingling peppercorns and hot pots.",
  "Poaching tofu builds deeper flavour than rushing the pan.",
  "Dukkah is Egyptian crushed nuts and spices for dipping.",
  "Channeling in espresso makes sour and bitter streaks.",
  "Gado-gado is an Indonesian salad dressed with peanut sauce.",
  "Baking beef keeps moisture when you respect temperature.",
  "Rice in salt shakers is an old humidity trick.",
  "Wet a knife to slice cheesecake cleanly.",
  "Underripe fruit often has more pectin for jam setting.",
  "Cloves are dried flower buds.",
  "Shallow frying needs oil halfway up the food.",
  "Baking paneer rewards patience more than constant poking.",
  "Frying eggs rewards patience more than constant poking.",
  "Pickling lamb tastes cleaner when you do not crowd the pan.",
  "Frying fish gets more aromatic if spices bloom in fat first.",
  "A Parmesan rind tossed into soup is a free umami booster.",
  "Grape leaves stuff into dolmas with rice and herbs.",
  "Bulgur is parboiled cracked wheat that cooks quickly.",
  "Offset smokers separate firebox and cook chamber.",
  "Bannock is a simple flatbread cooked on griddle or fire.",
  "Cabbage leaves wrap Eastern European sarma rolls.",
  "Sichuan peppercorns create a tingling, buzzing sensation.",
  "Whole wheat flour includes bran that drinks more water.",
  "Steaming lamb rewards patience more than constant poking.",
  "While you wait, picture a kitchen in Hanoi: clear broths and herb plates.",
  "Ada pradhaman is Kerala’s festival payasam with rice ada.",
  "Roasting chicken pairs well with a bright acid at the end.",
  "Tapas culture turns dinner into many small plates.",
  "Gunpowder temper with ghee can transform plain rice.",
  "Start emulsions slowly, then stream oil faster once thick.",
  "A peel dusted with semolina helps pizza slide free.",
  "Sun tea brews in jars left in sunlight — food-safety opinions vary.",
  "A clean grill marks food instead of tearing it.",
  "Carrot tops can become pesto instead of scrap.",
  "Oyster liquor is the salty liquid inside the shell.",
  "Cloud eggs bake whipped whites with yolks nestled in.",
  "Salsa verde can be Italian (herbs) or Mexican (tomatillo).",
  "Poaching paneer keeps moisture when you respect temperature.",
  "Halloumi squeaks and holds shape on the grill.",
  "Portobellos are mature creminis with broad caps.",
  "Steaming lamb shows off when salt is measured thoughtfully.",
  "Furikake is a Japanese rice sprinkle of seaweed and sesame.",
  "Carolina sauces can be vinegar-forward and tangy.",
  "Glass noodles turn translucent when soaked or cooked.",
  "Baijiu is a strong Chinese grain spirit.",
  "Poaching prawns builds deeper flavour than rushing the pan.",
  "Sfogliatelle are flaky, many-layered Neapolitan pastries.",
  "Peanuts grow underground and are legumes, not tree nuts.",
  "Fermenting fish shows off when salt is measured thoughtfully.",
  "Frying lamb gets more aromatic if spices bloom in fat first.",
  "Bao buns steam fluffy because yeast and moisture expand together.",
  "Roasting eggs shows off when salt is measured thoughtfully.",
  "Pickling prawns gets more aromatic if spices bloom in fat first.",
  "Ceviche traditions vary along the Pacific coast of the Americas.",
  "Roasting prawns tastes cleaner when you do not crowd the pan.",
  "Ceviche relies on acid, salt, and time — not stove heat.",
  "Frying paneer gets more aromatic if spices bloom in fat first.",
  "Keep a fire extinguisher rated for kitchen use nearby.",
  "Puff pastry rises from steam trapped between butter sheets.",
  "Champ is mash with spring onions and plenty of butter.",
  "Texas-style brisket often uses a simple salt-and-pepper rub.",
  "Fresh thyme makes compound butter instantly interesting.",
  "Poaching paneer loves a rest before you slice or serve.",
  "Smoking eggs gets more aromatic if spices bloom in fat first.",
  "Croutons toast better in fat than in a dry pan alone.",
  "Pickling pork gets more aromatic if spices bloom in fat first.",
  "Poaching beef keeps moisture when you respect temperature.",
  "Grilling pork keeps moisture when you respect temperature.",
  "Food is ready by temperature and feel, not only by clock.",
  "Breakfast sandwiches are urban fuel in bun form.",
  "Teriyaki shines from soy, sugar, and a glossy reduction.",
  "Steaming chicken gets more aromatic if spices bloom in fat first.",
  "Underproofed dough bursts unpredictably in the oven.",
  "Roshmalai soaks cheese balls in sweet milk.",
  "Reduce temperature ~15–20°C when converting to convection.",
  "Lady Grey softens the bergamot with other citrus peels.",
  "Saltimbocca means “jumps in the mouth” — veal with sage and prosciutto.",
  "Frying eggs gets more aromatic if spices bloom in fat first.",
  "Pickling prawns builds deeper flavour than rushing the pan.",
  "Neem flowers appear in some seasonal South Indian dishes.",
  "Soft-serve mix is held just above freezing in the machine.",
  "Smoking fish shows off when salt is measured thoughtfully.",
  "Baking eggs gets more aromatic if spices bloom in fat first.",
  "Oyster mushrooms sear into crispy edges.",
  "Fresh cilantro turns plain yogurt into a quick sauce.",
  "Candied ginger settles stomachs and spices cookies.",
  "Sufganiyot are jam-filled doughnuts for Hanukkah.",
  "Mukhwas are colourful post-meal seed mixes for digestion.",
  "A sharp knife is safer than a dull one that slips.",
  "Braising fish tastes cleaner when you do not crowd the pan.",
  "Vinegar-based hot sauces stay sharp and pourable.",
  "Summer rolls stay fresh because they are not deep-fried.",
  "Ice baths peel easier eggs by shrinking the white slightly.",
  "Hing blooms in oil and then mellows into savoury depth.",
  "Sterilising jars keeps preserves safe on the shelf.",
  "Reheat leftovers until steaming hot throughout.",
  "Frying pork rewards patience more than constant poking.",
  "Poaching eggs shows off when salt is measured thoughtfully.",
  "Poaching paneer gets more aromatic if spices bloom in fat first.",
  "Affogato is the simplest coffee dessert.",
  "Baking chicken loves a rest before you slice or serve.",
  "Pilaf browns rice in fat before adding liquid.",
  "Scallops brown best when thoroughly dried.",
  "Roasting lamb keeps moisture when you respect temperature.",
  "Cream cheese frosting needs chill time to set on cakes.",
  "Roasting fish builds deeper flavour than rushing the pan.",
  "Braising mushrooms builds deeper flavour than rushing the pan.",
  "Sour cream tang comes from lactic fermentation.",
  "Fermenting pork keeps moisture when you respect temperature.",
  "Ackee and saltfish is Jamaica’s famous breakfast plate.",
  "Braising beef builds deeper flavour than rushing the pan.",
  "Steaming prawns rewards patience more than constant poking.",
  "Shakshuka poaches eggs in spiced tomato sauce.",
  "Mincemeat once included meat; now it is mostly spiced fruit.",
  "Kale softens if massaged with oil and salt.",
  "Smoking chicken tastes cleaner when you do not crowd the pan.",
  "Coconut water has been used as emergency IV fluid in rare cases.",
  "Jal-jeera’s cumin and mint wake a tired palate.",
  "Salsa verde Italiana uses parsley, capers, and anchovy.",
  "Steaming mushrooms loves a rest before you slice or serve.",
  "Smoking eggs loves a rest before you slice or serve.",
  "New potatoes have thin skins and a sweet, firm bite.",
  "Older eggs often peel cleaner than very fresh ones.",
  "Lighter fluid can perfume food if you rush the burn-off.",
  "Farce is another culinary word for stuffing mixtures.",
  "Deviled eggs pipe yolk mayonnaise back into whites.",
  "Never dump leftover soy-wasabi back onto shared fish.",
  "Spicy foods make you sweat as your body tries to cool down.",
  "Rehydrating mushroom liquid is liquid gold for sauces.",
  "Frying tofu tastes cleaner when you do not crowd the pan.",
  "Frying pork builds deeper flavour than rushing the pan.",
  "Briquettes burn steadier for long barbecues.",
  "Shortening is engineered to stay solid and tenderise dough.",
  "Rhode Island clam chowder is clear-broth in some traditions.",
  "Christmas pudding steams for hours and flames with brandy.",
  "Baghan is a finishing temper poured over dal.",
  "Charcoal chimneys light fuel without lighter-fluid taste.",
  "Poaching chicken shows off when salt is measured thoughtfully.",
  "Valencian paella traditionally includes rabbit and snails.",
  "Clafoutis bakes fruit in a thick pancake-like batter.",
  "Samosa and empanada both prove fried pockets travel cultures.",
  "Mozzarella for pizza often uses low-moisture for less sogginess.",
  "Gochujang is Korean chili paste with fermented depth.",
  "Pickling lamb rewards patience more than constant poking.",
  "Fermenting lamb gets more aromatic if spices bloom in fat first.",
  "Aviyal mixes vegetables in coconut and yogurt.",
  "A good queue needs a seal that survives boiling or steaming.",
  "Poaching lamb shows off when salt is measured thoughtfully.",
  "Kashmiri pink chai gets its colour from a baking-soda reaction.",
  "Fresh chèvre is tangy goat cheese that spreads easily.",
  "Cool leftovers quickly before refrigerating in shallow containers.",
  "Frittatas welcome leftover vegetables into egg form.",
  "Steaming fish gets more aromatic if spices bloom in fat first.",
  "Frying lamb shows off when salt is measured thoughtfully.",
  "Basbousa is semolina cake soaked in fragrant syrup.",
  "Overcooked shrimp go from plump to rubbery quickly.",
  "Éclairs pipe choux into fingers filled with cream.",
  "Okra also thickens gumbo with natural mucilage.",
  "While you wait, picture a kitchen in Tokyo: seasonal sushi and meticulous broths.",
  "Gaiwan brewing tastes tea in short multiple steeps.",
  "Autolyse rests flour and water before salt and yeast.",
  "Bagels get their chew from boiling before baking.",
  "Grilling pork gets more aromatic if spices bloom in fat first.",
  "Gulab jamun drinks syrup after frying — patience makes them juicy.",
  "Steaming eggs tastes cleaner when you do not crowd the pan.",
  "Soju is a clear Korean spirit often shared with meals.",
  "Kebab simply means meat cooked over or near fire.",
  "Steaming chicken rewards patience more than constant poking.",
  "Fresh thyme loves citrus zest as a partner.",
  "Basmati means “fragrant” in Hindi.",
  "Poaching paneer pairs well with a bright acid at the end.",
  "Compound butter melts into an instant sauce on hot meat.",
  "Diane sauce is a flambéed steak classic.",
  "Baking chicken rewards patience more than constant poking.",
  "Olive oil cake tastes fruity and stays moist for days.",
  "Guntur chili packs serious Andhra heat.",
  "Cutlets bread mashed veg or meat for a crisp pan fry.",
  "Steaming fish rewards patience more than constant poking.",
  "Roasting paneer loves a rest before you slice or serve.",
  "Grilling tofu loves a rest before you slice or serve.",
  "Sous-vide steak then sear for edge-to-edge doneness.",
  "Zucchini fritters need salted, squeezed veg to stay crisp.",
  "Cacio e pepe emulsifies cheese, pepper, and pasta water.",
  "Charcuterie boards balance salty, fatty, acidic, and crunchy.",
  "Cornstarch in some fondues helps keep cheese from breaking.",
  "Shrimp boils season the water aggressively so flavour penetrates.",
  "Spelt is another heritage wheat used in breads.",
  "Pizza steel transfers heat faster than many stones.",
  "Millet revival is bringing old grains back to modern plates.",
  "Filé powder thickens gumbo with ground sassafras.",
  "AeroPress is portable and surprisingly café-capable.",
  "While you wait, picture a kitchen in Jaipur: ghee-rich sweets and royal thalis.",
  "Baking mushrooms tastes cleaner when you do not crowd the pan.",
  "Jowar and bajra breads are naturally gluten-free.",
  "A candy thermometer marks thread, soft-ball, and hard-crack stages.",
  "Smoking prawns gets more aromatic if spices bloom in fat first.",
  "Baked ziti is a casserole of tube pasta and cheese.",
  "Pickled ginger resets sushi palates between pieces.",
  "Frying lamb rewards patience more than constant poking.",
  "Bisques are smooth, often shellfish-based cream soups.",
  "Gefilte fish jelly sets from the poaching broth.",
  "Grams remove the debate about packed brown sugar.",
  "Ascorbic acid in some doughs strengthens gluten.",
  "Persillade is parsley and garlic, often with breadcrumbs.",
  "Steaming fish keeps moisture when you respect temperature.",
  "Smoking beef loves a rest before you slice or serve.",
  "Oncom is an Indonesian fermented cake related to tempeh traditions.",
  "Steaming mushrooms tastes cleaner when you do not crowd the pan.",
  "Fermenting pork gets more aromatic if spices bloom in fat first.",
  "Fresh dill loves citrus zest as a partner.",
  "Steaming lamb pairs well with a bright acid at the end.",
  "Risotto is stirred to coax creamy starch from short-grain rice.",
  "Ice cream headaches are a cold-triggered nerve response.",
  "Fondue is Swiss melted cheese (or chocolate) for dipping.",
  "Frying eggs shows off when salt is measured thoughtfully.",
  "Russets bake into fluffy jackets.",
  "Frying lamb keeps moisture when you respect temperature.",
  "Fresh chives softens when warmed gently in oil.",
  "Poaching fish keeps moisture when you respect temperature.",
  "Rum raisins plump when soaked and perfume cakes.",
  "Frying mushrooms shows off when salt is measured thoughtfully.",
  "Cannelloni are large tubes stuffed and baked in sauce.",
  "Fresh mint can stand in for salad greens in a pinch.",
  "Shochu can be distilled from sweet potato, barley, or rice.",
  "Fried curry leaves perfume an entire kitchen in seconds.",
  "Grilling pork rewards patience more than constant poking.",
  "Tadka / chaunk / baghaar temper spices in hot fat.",
  "Roux is flour cooked in fat — the base of many gravies.",
  "Tube pans help dense batters bake through evenly.",
  "Brining seasons meat deeper than a surface sprinkle.",
  "Hydration in bread is water weight divided by flour weight.",
  "Tempura batter stays lumpy on purpose for lacy crunch.",
  "Pumpernickel is a dark, slow-baked rye loaf.",
  "Frying prawns tastes cleaner when you do not crowd the pan.",
  "Roasting tofu keeps moisture when you respect temperature.",
  "Roasting lamb builds deeper flavour than rushing the pan.",
  "Baked Alaska hides ice cream under toasted meringue.",
  "Baking beef builds deeper flavour than rushing the pan.",
  "Smoking fish rewards patience more than constant poking.",
  "Fermenting pork tastes cleaner when you do not crowd the pan.",
  "Milk steaming stretches then textures into microfoam.",
  "Bitterballen are Dutch deep-fried stew croquettes.",
  "Pickling beef rewards patience more than constant poking.",
  "An ice bath stops boiled eggs from overcooking.",
  "Pesto traditionally pounds basil, pine nuts, garlic, cheese, and oil.",
  "Braising eggs builds deeper flavour than rushing the pan.",
  "Pickling eggs builds deeper flavour than rushing the pan.",
  "While you wait, picture a kitchen in Bangkok: balance of sweet, sour, salty, and heat.",
  "Fermenting pork loves a rest before you slice or serve.",
  "Scampi traditionally refers to a type of lobster relative — names blur in restaurants.",
  "Umami is the savoury taste from glutamates in tomatoes and mushrooms.",
  "Crumb coats trap loose crumbs before the final frosting.",
  "Chicken wing joints reveal doneness when they loosen.",
  "Grilling lamb loves a rest before you slice or serve.",
  "Fermenting mushrooms builds deeper flavour than rushing the pan.",
  "Poaching lamb gets more aromatic if spices bloom in fat first.",
  "Self-raising flour already contains baking powder.",
  "Empanadas seal fillings inside pastry half-moons.",
  "Braising mushrooms pairs well with a bright acid at the end.",
  "Pellet smokers automate feed for convenience.",
  "Fresh mint makes compound butter instantly interesting.",
  "Poaching paneer builds deeper flavour than rushing the pan.",
  "Fermenting fish builds deeper flavour than rushing the pan.",
  "Pickling chicken loves a rest before you slice or serve.",
  "Fermenting chicken pairs well with a bright acid at the end.",
  "Marrakech is famous for spice markets and tagine steam — a reminder that place seasons food.",
  "A good vinaigrette ratio often starts near 3:1 oil to acid.",
  "Dried mushrooms intensify broth with deep forest umami.",
  "Kashmiri chili colour can fake heat — taste before you dump.",
  "Kalakand sets milk and chhana into a moist barfi.",
  "A water bath and slow cool help cheesecakes stay smooth.",
  "Frying beef gets more aromatic if spices bloom in fat first.",
  "Fermenting tofu shows off when salt is measured thoughtfully.",
  "Rotla is another name for millet flatbreads in some regions.",
  "Smoking mushrooms builds deeper flavour than rushing the pan.",
  "Pickling prawns tastes cleaner when you do not crowd the pan.",
  "Vada pav is Mumbai’s handheld potato fritter in a bun.",
  "Hot soapy water handles most raw poultry board cleanups.",
  "Holy basil (tulsi) is sacred and medicinal in India.",
  "Steaming paneer shows off when salt is measured thoughtfully.",
  "Wasabi’s heat hits the nose; chili heat lingers on the tongue.",
  "Clove and cardamom perfume biryani steam.",
  "Swedish fika is a pause for coffee and something sweet.",
  "Frying fish loves a rest before you slice or serve.",
  "Cold butter in pastry melts into flaky steam pockets.",
  "Frying beef loves a rest before you slice or serve.",
  "Fresh parsley brightens grilled vegetables.",
  "Sorbet skips dairy and leans on fruit and sugar syrup.",
  "Doro wat is Ethiopian chicken stew with berbere spice.",
  "Biryani steams layered rice and meat so perfume rises through both.",
  "Warm bacon dressing wilts spinach into a classic salad.",
  "French press steeping then plunging yields a heavier body.",
  "Steaming chicken shows off when salt is measured thoughtfully.",
  "The holy trinity is onion, celery, and bell pepper.",
  "Weekend paella outdoors is as much social as culinary.",
  "Swiss chard stems need longer cooking than the leaves.",
  "Dum biryani seals with dough to trap steam.",
  "Ginger and garlic freeze grated for instant seasoning.",
  "Pastry blenders cut butter into flour for biscuits.",
  "Roasting bones first makes darker, meatier stock.",
  "Steaming pork rewards patience more than constant poking.",
  "Peppermint tea can soothe after heavy meals.",
  "Fermenting lamb builds deeper flavour than rushing the pan.",
  "Braising tofu rewards patience more than constant poking.",
  "Shaoxing wine seasons Chinese stir-fries and marinades.",
  "Tableside flambé is theatre as much as flavour.",
  "Green papaya salad pounds chilies, lime, and fish sauce together.",
  "Steaming paneer tastes cleaner when you do not crowd the pan.",
  "Waldorf salad mixes apple, celery, and walnuts.",
  "Makrut lime leaves bruise to release fragrant oils.",
  "Pie weights hold pastry flat while it sets in the oven.",
  "Baking pork builds deeper flavour than rushing the pan.",
  "Fermenting eggs keeps moisture when you respect temperature.",
  "Momos travelled across the Himalayas into Indian cities.",
  "Massage tough greens to bruise cell walls and soften them.",
  "Sweet potatoes are not the same species as yams.",
  "Frying chicken tastes cleaner when you do not crowd the pan.",
  "Steaming lamb gets more aromatic if spices bloom in fat first.",
  "Soba dipping sauce is mentisuyu — soy, dashi, and mirin.",
  "Poaching eggs pairs well with a bright acid at the end.",
  "Acetic acid is the sharp bite in vinegar.",
  "Soda bread rises with baking soda and buttermilk acid.",
  "Cold smoking flavours without cooking; hot smoking does both.",
  "Roasting tofu pairs well with a bright acid at the end.",
  "Steaming beef gets more aromatic if spices bloom in fat first.",
  "Coppa / capocollo is cured pork neck / shoulder.",
  "A water pan in a smoker steadies temperature and moisture.",
  "Braising chicken pairs well with a bright acid at the end.",
  "Maki rolls wrap fillings in nori and rice.",
  "Sushi rice is short-grain and seasoned while warm.",
  "Youtiao are Chinese fried dough sticks for soy milk breakfasts.",
  "Pickling paneer shows off when salt is measured thoughtfully.",
  "Ground spices burn faster than whole seeds.",
  "Pickling lamb builds deeper flavour than rushing the pan.",
  "Carrot cake’s sweetness comes partly from the carrots themselves.",
  "Handvo is a savoury baked lentil-rice cake.",
  "Frying chicken gets more aromatic if spices bloom in fat first.",
  "Grilling prawns tastes cleaner when you do not crowd the pan.",
  "Fresh basil brightens grilled vegetables.",
  "Quinoa stuffing keeps gluten-free holiday plates hearty.",
  "Pickling mushrooms gets more aromatic if spices bloom in fat first.",
  "Baking beef shows off when salt is measured thoughtfully.",
  "Charlotte moulds cake or biscuits around a creamy filling.",
  "Smoking chicken shows off when salt is measured thoughtfully.",
  "Grilling prawns pairs well with a bright acid at the end.",
  "Poaching chicken pairs well with a bright acid at the end.",
  "Manicotti is a similar stuffed-tube idea in Italian-American kitchens.",
  "Lye on pretzels creates deep brown and distinctive flavour.",
  "Cast iron seasoning is polymerised oil, not a coating of magic.",
  "Mysore pak is gram flour, sugar, and a lot of ghee.",
  "Tahini sauce on roasted vegetables is weeknight gold.",
  "Braising mushrooms tastes cleaner when you do not crowd the pan.",
  "Lasagne sheets can be fresh or dried; fresh needs less time.",
  "Fermenting paneer tastes cleaner when you do not crowd the pan.",
  "Frying paneer shows off when salt is measured thoughtfully.",
  "Smoking eggs shows off when salt is measured thoughtfully.",
  "Mochi ice cream wraps gelato in a chewy rice dough.",
  "Msg is sodium glutamate — a pure umami seasoning.",
  "Pickling chicken rewards patience more than constant poking.",
  "Vanilla extract is alcohol carrying vanillin from beans.",
  "Suprême sauce is velouté with cream.",
  "Cheesecake cracks when overbaked or cooled too fast.",
  "Grilling fish rewards patience more than constant poking.",
  "Baking tofu keeps moisture when you respect temperature.",
  "Sencha is steamed Japanese green tea.",
  "A channel knife cuts decorative citrus twists.",
  "A liaison of yolk and cream enriches without full boiling.",
  "Proofing is the final rise before baking.",
  "Spaetzle are German egg batter noodles scraped into water.",
  "Thyme’s flavour survives long simmers better than basil.",
  "Roasting pork rewards patience more than constant poking.",
  "Saffron soaked in warm milk bleeds colour into rice.",
  "Fresh mint turns plain yogurt into a quick sauce.",
  "Never soak wooden boards for long — they warp.",
  "Unadon tops rice with glazed grilled eel.",
  "Twice-baked soufflés can be reheated more calmly.",
  "Smoking chicken rewards patience more than constant poking.",
  "Frying mushrooms rewards patience more than constant poking.",
  "Kokum soda is a refreshing western Indian cooler.",
  "Fermenting paneer loves a rest before you slice or serve.",
  "American buttercream is butter beaten with powdered sugar.",
  "Sikhye is a sweet Korean rice beverage.",
  "Fermentation preserves food and creates new flavours microbes invent.",
  "Grilling tofu shows off when salt is measured thoughtfully.",
  "Rest breaded cutlets briefly so coating sticks.",
  "Steak and eggs is diner shorthand for protein power.",
  "Frying chicken pairs well with a bright acid at the end.",
  "Pavlova is a crisp meringue shell with soft marshmallow centre.",
  "Grilling beef loves a rest before you slice or serve.",
  "Kulfi moulds freeze slowly for a dense ice cream bar.",
  "Minestrone is a vegetable soup that changes with the market.",
  "Mille-feuille means a thousand leaves of puff pastry.",
  "Roasting chicken rewards patience more than constant poking.",
  "Stuffed cabbage rolls simmer in tomato or broth.",
  "Pickling mushrooms loves a rest before you slice or serve.",
  "Braising paneer shows off when salt is measured thoughtfully.",
  "Smoking lamb pairs well with a bright acid at the end.",
  "Baking fish rewards patience more than constant poking.",
  "Masa harina is dried nixtamalised corn flour.",
  "Never mix bleach with vinegar or ammonia.",
  "Omelettes fold; frittatas finish set, often in the oven.",
  "Poaching mushrooms shows off when salt is measured thoughtfully.",
  "Packing plants bounce cranberries — ripe ones rebound.",
  "Frying mushrooms keeps moisture when you respect temperature.",
  "Bark on brisket is the dark, seasoned crust from low smoke.",
  "Pickling chicken shows off when salt is measured thoughtfully.",
  "White roux is pale; brown roux tastes nuttier and thickens less.",
  "Steaming prawns tastes cleaner when you do not crowd the pan.",
  "Garam masala is usually added toward the end for aroma.",
  "Ghee-roasted spices smell different from oil-tempered spices.",
  "Pickling beef keeps moisture when you respect temperature.",
  "Pickling mushrooms builds deeper flavour than rushing the pan.",
  "Pomodoro simply means tomato — and a style of sauce.",
]
