name: Deploy Frontend (Prod)

on:
  workflow_dispatch: # Enables the manual "Run workflow" button in GitHub Actions

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Production Build
        run: |
          curl -X POST "${{ secrets.VERCEL_PROD_DEPLOY_HOOK }}"